### PR TITLE
langgraph: fix add_node input schema error

### PR DESCRIPTION
**Pull request by gbaian10**
fix: #1331

I used `inspect.signature` to read the name of the first parameters and determine whether this variable has a type_hint.

And used `StopIteration` to prevent situations where there are no parameters.
Although in this situation, executing invoke will still result in an error.

If want to catch errors before running the graph, maybe you can check that the number of parameters is not zero?

### CODE REVIEW

**Comment by gbaian10** [comment]
Regarding first_parameter_name = next(iter(inspect.signature(action).parameters.keys()))

Also can use list() and then check the length before accessing [0].

I'm not sure which one is better.

**Review by nfcampos — APPROVED** [review]
Thanks, do you want to add a test case?

**Comment by gbaian10** [comment]
> Thanks, do you want to add a test case?

I plan to add tests using this logic. Do you have any better suggestions?

```py
from typing import TypedDict

from langchain_core.runnables import RunnableConfig
from langgraph.graph import StateGraph

# from libs.langgraph.langgraph.graph.state import StateGraph


class InputState(TypedDict):
    question: str


class OutputState(TypedDict):
    input_state: dict


def foo(state: InputState) -> OutputState:
    return {"input_state": state}


def bar(state, config: RunnableConfig) -> OutputState:
    # The expected `state` result is `InputState`, but received `RunnableConfig`.
    return {"input_state": state}


def baz(state, config) -> OutputState:
    # The expected `state` result is `InputState`, but received `OutputState`.
    return {"input_state": state}


graph = StateGraph(input=InputState, output=OutputState)
graph.add_node(foo)
graph.add_node(bar)
graph.add_node(baz)

graph.set_entry_point(foo.__name__)
graph.add_edge(foo.__name__, bar.__name__)
graph.add_edge(bar.__name__, baz.__name__)
graph.set_finish_point(baz.__name__)

graph = graph.compile()

for v in graph.stream({"question": "foo"}, stream_mode="values"):
    print(v)
    if "input_state" in v:
        assert v["input_state"] == {"question": "foo"}
```

**Comment by vbarda** [comment]
Thank you @gbaian10  -- going to merge!

**Pull request merged**
