### PR TITLE
Update `persistence_redis.ipynb` example to work with the latest version

### PR DESCRIPTION
**Pull request by DhavalThkkar**
1. Added `put_writes` and `aput_writes` to match the latest update.
2. Added some optimizations using DRY principle

Fix for #1134

### CODE REVIEW

**Comment by DhavalThkkar** [comment]
@slgabbar @OmarHory @dzubke Updated the code as per the issues, please check and let me know if there's something else you'd like me to see. We can collaborate and contribute if required

**Comment by DhavalThkkar** [comment]
@vbarda Need to pull to main, all checks are cleared

**Comment by vbarda** [comment]
> @vbarda Need to pull to main, all checks are cleared

@DhavalThkkar we're in the process of updating checkpointer interfaces, so we'll likely need to update again. will post an update

**Comment by vbarda** [comment]
> > @vbarda Need to pull to main, all checks are cleared
> 
> @DhavalThkkar thanks! we're in the process of updating checkpointer interfaces, so we'll likely need to update again. will post an update

@DhavalThkkar I updated the guide with the latest functionality -- it required a few more changes to make it work correctly, but I used your implementation extensively to do so! Thank you very much for your contributions. See this PR https://github.com/langchain-ai/langgraph/pull/1286 or just this page https://langchain-ai.github.io/langgraph/how-tos/persistence_redis/. I am going to close this PR in the meantime.

**Pull request closed without merging**
