### PR TITLE
Feat/Add @workflow.register_node decorator

### PR DESCRIPTION
**Pull request by Howe829**
Adding graph.register_node decorator for easily register a node to the workflow.

### CODE REVIEW

**Comment by hinthornw** [comment]
oh it's kinda convenient. Will defer to @nfcampos on the approval though

**Comment by nfcampos** [comment]
I'm not opposed to this as long as we can do it inside the existing add_node method

**Comment by Howe829** [comment]
Hi there, I've tried to make it inside the add_node method.PLTAL
It may looks  a little bit tricky but this is the best way for me  to make add_node as a decorator as well as thinking about the forward compatibility.

**Comment by Glinte** [comment]
Any updates on this? Seems quite helpful

**Comment by vbarda** [comment]
Thanks for your contribution! Going to close since this is already supported in the library https://github.com/langchain-ai/langgraph/blob/main/libs/langgraph/tests/test_pregel.py#L2189

**Pull request closed without merging**
