### PR TITLE
Extend existing unit tests using cover-agent

### PR DESCRIPTION
**Pull request by mrT23**
The PR content was generated automatically using [cover-agent](https://github.com/Codium-ai/cover-agent)

## Methodology

Cover-agent automatically scans a repository to detect existing unit test files. It gathers relevant context for each file, then triggers an AI-based workflow to enhance these tests by adding new cases that increase code coverage and address uncovered behaviors.

## Reliability 

But it's AI-generated code. How can we know it's reliable ? How can we know it's effective ?

Answer:

All AI-generated tests have met these four essential criteria:

1. Execute successfully
2. Pass all assertions
3. Increase overall code coverage
4. Test previously uncovered behaviors (as specified in the LLM prompt)

## Increased coverage
Code coverage comparison  of the relevant source files before and after these changes:
image

In total, 129 new lines were covered with the tests added in this PR

## Appendix: unit tests - what are they good for?
<details><summary>Answer:</summary>

Personal opinion - writing unit testing is not fun. It becomes even less appealing as your codebase grows and maintaining tests becomes a time-consuming chore.

However, the benefits of comprehensive unit tests are real: 
- Reliability: They create a more reliable codebase where developers can make changes confidently
- Speed: Teams can move quickly without fear of breaking existing functionality
- Safe Refactoring: Code improvements and restructuring become significantly safer when backed by thorough tests
- Living Documentation: Tests serve as clear documentation of your code's behavior:

  - They show exactly what happens for each input
  - They present changes in a human-readable format: "for this input → expect this output"
  - They run quickly and are easy to execute
  - This immediate feedback loop is beneficial during development

</details>

### CODE REVIEW

**Comment by nfcampos** [comment]
hi, I'm not opposed to merging some of these, but there's some things you'll have to fix before you can do that
- files are not formatted using our formatter
- you're adding an anyio marker in some tests, but we add it top-level in the file so not needed

**Comment by mrT23** [comment]
@nfcampos 
thanks for the quick feedback.

i passed the files through a linter, and removed direct usage of `anyio marker`

(I will also use this feedback to further improve the auto tool, giving him more 'encouragement' to maintain the current used style)

**Comment by mrT23** [comment]
@nfcampos
Can you run the checks on the updated version ?

**Comment by mrT23** [comment]
image

i dont think this is related to the PR

**Comment by mrT23** [comment]
@eyurtsev 
Are you interested in this PR or not ?
Its been hanging for a while

**Pull request closed without merging**
