### PR TITLE
Allow the structured output resonse with create_react_agent 

### PR DESCRIPTION
**Pull request by mohit-mangal**
Added `response_format` in `create_react_agent` method to allow the chat model to return structured output in JSON string based on pydantic BaseModel.

If `response_format` is provided, the AIMessaged returned chat model would have a JSON string in its `content`.

### Example of structured output - 
```
#example.py
from typing import Optional, TypedDict, Any, Type
from pydantic import BaseModel, Field

import json

from langgraph.prebuilt import create_react_agent, ToolNode
from langchain_core.tools import BaseTool
from langchain_openai import ChatOpenAI


class ResponseSchema(BaseModel):
    is_related_query: bool = Field(description='Indicates if user query was related to the domestic pets')
    response: str = Field(description='content response of the chat assistant')


class UpdateFavoritePetTool(BaseTool):
    name: str = 'UpdateFavoritePetTool'
    description: str = 'Updates the favorite pet of the tool for current user'

    class InputSchema(BaseModel):
        pet_name: str = Field(description='Name of the pet')

    args_schema: Type[BaseModel] = InputSchema

    def _run(self, pet_name: str, **kwargs):
        print('updating the favorite pet of the user to', pet_name)
        return {'success': True}

my_tools = [UpdateFavoritePetTool()]

system_prompt = """
You are a helpful assistant specializing in the field of domestic pets.
You have some tools available for certain actions.
YOU SHOULD NOT ANSWER ANTHING ELSE OTHER THAN QUERIES RELATED TO DOMESTIC PETS.

Your response format should strictly in JSON format.
"""

open_ai_model = ChatOpenAI(model="gpt-4o-2024-08-06", openai_api_key=OPEN_AI_KEY)
assistant = create_react_agent(
            open_ai_model,
            my_tools,
            state_modifier=system_prompt,
            response_format=ResponseSchema
          )

user_input = input("Enter your query:\n")    
assistant_response = assistant.invoke({"messages": [("user", user_input)]})
messages = assistant_response.get('messages')
parsed_ai_response = json.loads(messages[-1].content)
print('\nAI response: ',parsed_ai_response)
print('is query related to domestic pets', parsed_ai_response['is_related_query'])
```

### ---------------- Run the file ---------------- 
```
$ python example.py
Enter your query:
How's the weather

AI response: {'is_related_query': False, 'response': "I'm here to assist with questions about domestic pets."}
is query related to domestic pets: False
```

### ---------------- Run the file again ---------------- 
```
$ python example.py
Enter your query:
Update my favorite pet to Labrador dogs

AI response: {'is_related_query': True, 'response': 'Your favorite pet has been updated to Labrador dogs.'}
is query related to domestic pets: True

```

### CODE REVIEW

**Comment by vbarda** [comment]
@mohit-mangal thanks for your contribution! you can actually pass model with bound tools directly to react agent, like this
`create_react_agent(model.bind_tools(tools, any_extra_kwargs), tools)`. 

will close this PR since it's already supported, but let me know if you run into issues w/ this

**Comment by mohit-mangal** [comment]
> you can actually pass model with bound tools directly to react agent, like this
> create_react_agent(model.bind_tools(tools, any_extra_kwargs), tools).
@vbarda I understand this but this is not mentioned in documentation and not widely known as well.

I searched for a structured output format from the `ReAct` agent,  and all I found was that it's not possible through various discussion forms - 
Langchain documentation - https://langchain-ai.github.io/langgraph/how-tos/react-agent-structured-output/
GitHub documentation - https://github.com/langchain-ai/langchain/discussions/25359

We should have either one of those, `response_format` or `documentation`.
My recommendation as a consumer is to have `response_format` in the arguments of `create_react_agent`

**Comment by vbarda** [comment]
@mohit-mangal let me reopen this for now! i do think this needs to be better documented and we might still need a more explicit control in `create_react_agent`. appreciate the feedback. let us regroup, will get back to you here!

**Comment by mohit-mangal** [comment]
@vbarda did you get a chance to discuss with your team?

**Comment by mohit-mangal** [comment]
@vbarda any updates on this?

**Comment by mohit-mangal** [comment]
> @mohit-mangal no updates yet, if this is blocking you and if this PR is sufficient for your use case i would recommend doing this [#2674 (comment)](https://github.com/langchain-ai/langgraph/pull/2674#issuecomment-2525326662)

@vbarda thanks for the updates!
I am currently using the said method. Let me know when there's any progress on this.

**Comment by vbarda** [comment]
@mohit-mangal i am going to close this PR because it won't work for providers other than OpenAI. I will post an update once we implement the support in `create_react_agent`, it will be based off of this https://langchain-ai.github.io/langgraph/how-tos/react-agent-structured-output/

**Comment by mohit-mangal** [comment]
Thanks @vbarda for fixing this last month.
Attaching your commit for everyone's reference - https://github.com/langchain-ai/langgraph/commit/10d46acc60d19db426b6508b8b81de96aa1bab6d

**Pull request closed without merging**
