### PR TITLE
Fix: is last step logic to run per execution

### PR DESCRIPTION
**Pull request by abprime**
Use both step and stop value to decide the last step (per execution)

Current logic for last step checks the step number against recursion_limit in the config.
The step number keeps incrementing every execution, so it won't set the is_last_step correctly every execution.

Discussion on the same:
https://github.com/langchain-ai/langgraph/discussions/2025

### CODE REVIEW

**Comment by abprime** [comment]
Hi @nfcampos , 
Could you please review this and let me know your feedback. 
I was able to find this solution for the issue.

**Comment by abprime** [comment]
Hi @hinthornw ,

could you please take a look at this PR and give your feedback?

**Comment by antonioalegria** [comment]
May be worthwhile to open an issue from that discussion.

**Comment by abprime** [comment]
https://github.com/langchain-ai/langgraph/issues/2081

**Comment by nfcampos** [comment]
Thanks, we can't modify the checkpoint format for this purpose, fixed in a different way in #2105

**Pull request closed without merging**
