### PR TITLE
fix(docs): function call in partial

### PR DESCRIPTION
**Pull request by allenc97**
Docs use prompts with partial + function call, which would result in a static datetime as opposed to a dynamic datetime being rendered on use.

### CODE REVIEW

**Comment by vbarda** [comment]
@allenc97 that wouldn't work, as `datetime.now` is a function, so it would need to be actually invoked

**Comment by allenc97** [comment]
Partial takes in a string or a callable - this is the latter. The original behavior would result in an evaluation during the .partial function call and not on substitution.

**Comment by vbarda** [comment]
you're right, my apologies - will reopen and merge!

**Review by vbarda — APPROVED** [review]

**Comment by vbarda** [comment]
Thanks for adding!

**Pull request merged**
