### PR TITLE
feat: add dynamodb checkpoint saver

### PR DESCRIPTION
**Pull request by adosaiguas**
Checkpoint saver that stores history in AWS DynamoDB

### CODE REVIEW

**Comment by hinthornw** [comment]
Thanks for the PR, @adosaiguas ! Excited for your involvement.

We plan to limit the scope of the `langgraph` package + repo to be core implementations + API's (similar to langchain-core). 

What we could do is implement this in langchain-community at the path `langchain_community.checkpoints` ([this is the code path](https://github.com/langchain-ai/langchain/tree/master/libs/community/langchain_community))

Then we could include examples there and/or in here of how to use.

Does that make sense?

**Comment by adosaiguas** [comment]
@hinthornw thank you for your reply! sure, I'll move it there. I'll close this PR once I have the other PR link.

**Comment by hinthornw** [comment]
Thank you!

**Comment by vbarda** [comment]
@adosaiguas thank you for your contribution!

we recently rolled out a change in [langgraph v0.2](https://github.com/langchain-ai/langgraph/releases/tag/0.2.0) that moves checkpointers into separate, official python packages (see [here](https://github.com/langchain-ai/langgraph/tree/main/libs/checkpoint-postgres) and [here](https://github.com/langchain-ai/langgraph/tree/main/libs/checkpoint-sqlite)). we will mostly be working with our partners to implement and maintain these packages in an official capacity.

if you want to share your implementation in an unofficial capacity, please start a new discussion for that. if you would like to create a library and maintain it in an official capacity, please get in touch with us!

either way i am going to close this PR for now -- feel free to start a new discussion!

**Pull request closed without merging**
