### PR TITLE
fix: the execution error passed from ToolExecutor to create_react_agent

### PR DESCRIPTION
**Pull request by gbaian10**
fix #1224 #1225

### CODE REVIEW

**Review by vbarda — APPROVED** [review]

**Comment by vbarda** [comment]
thanks for fixing!

**Comment by vbarda** [comment]
@gbaian10 do you mind resolving the conflicts on this PR?

**Comment by gbaian10** [comment]
> @gbaian10 do you mind resolving the conflicts on this PR?

It seems to have changed a lot, should I open a new PR? (A whole lib folder has been added?)

**Comment by gbaian10** [comment]
I opened a new PR.

**Pull request closed without merging**
